export const SIGN_NAME = '兴趣班学习平台'
export const TEMPLATECODE = ''
export const ACCESS_KEY_ID = 'LTAI5tHx2pEgFVS5LTcWwchb'
export const ACCESS_KEY_SECRET = '3iPhJVIeswujZppq4Yzd8u5JMNX6G5'
export const BUCKET = 'learn-platform-assets'
