name: Sync code to Gitee

on:
  push:
    branches:
      - main


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync code to Gitee
        env:
          GITEE_USERNAME: wushengzhu
          GITEE_ACCESS_TOKEN: ${{  secrets.GITEE_ACCESS_TOKEN  }}
        run: |
          git remote add gitee https://wushengzhu:${GITEE_ACCESS_TOKEN}@gitee.com/wushengzhu/learn-platform.git
          git push gitee HEAD:main --force
