name: Sync code to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync code to Gitee
        run: |
          git remote add gitee https://gitee.com/wushengzhu/learn-platform.git
          git push gitee HEAD:main --force
