name: Sync to Gitee

on:
  push:
    branches: 
      - main
  # schedule:
  #   - cron: "0 0 * * *"  # 每天 UTC 时间 00:00 执行
  # workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH scan for gitee.com
        run: |
          ssh-keyscan gitee.com >> ~/.ssh/id_rsa
      - name: Sync to Gitee
        run: |
          git remote add gitee git@gitee.com:wushengzhu/learn-platform.git  # 替换为你的 Gitee 仓库地址
          git push gitee HEAD:master

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Sync code from GitHub to Gitee"
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
